/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import Modelo.Usuario;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form F_bienvenida
     */
    private static int mouseX, mouseY;
    private static boolean mousePressed;
    private Usuario usuarioLogeado;

    public Bienvenida() {
        initComponents();
        habilitarArrastre(this);
    }

    public Bienvenida(Usuario usuarioLogeado_e) {
        this.usuarioLogeado = usuarioLogeado_e;
        initComponents();
        bienvenida();
        habilitarArrastre(this);
    }

    public Bienvenida(Usuario usuarioLogeado_e, Color colorFondo) {
        this.usuarioLogeado = usuarioLogeado_e;
        initComponents();
        bienvenida();
        habilitarArrastre(this);
        cambiarColorInterfaz(colorFondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_panelLeft_Bienvenida = new javax.swing.JPanel();
        B_cambiarPass_Bienvenida = new javax.swing.JButton();
        L_ICON_Bienvenida = new javax.swing.JLabel();
        B_cerrarSesion_Bienvenida = new javax.swing.JButton();
        B_cuentaNueva_Bienvenida = new javax.swing.JButton();
        L_userLog_Bienvenida = new javax.swing.JLabel();
        TF_nombreUsuario_Bienvenida = new javax.swing.JTextField();
        P_panelTop_Bienvenida = new javax.swing.JPanel();
        L_ICON_Min_MenuLogin = new javax.swing.JLabel();
        L_ICON_X_MenuLogin1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SP_infoArchivo_Bienvenida = new javax.swing.JScrollPane();
        TA_infoArchivo_Bienvenida = new javax.swing.JTextArea();
        MB_barraMenu_Bienvenida = new javax.swing.JMenuBar();
        M_archivo_Bienvenida = new javax.swing.JMenu();
        MI_abrir_bienvenida = new javax.swing.JMenuItem();
        MI_guardar_Bienvenida = new javax.swing.JMenuItem();
        M_edicion_Bienvenida = new javax.swing.JMenu();
        MI_cambColorUI_Bienvenida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        P_panelLeft_Bienvenida.setBackground(new java.awt.Color(57, 167, 255));
        P_panelLeft_Bienvenida.setLayout(null);

        B_cambiarPass_Bienvenida.setBackground(new java.awt.Color(255, 238, 217));
        B_cambiarPass_Bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B_cambiarPass_Bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        B_cambiarPass_Bienvenida.setText("Cambiar Contraseña");
        B_cambiarPass_Bienvenida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_cambiarPass_Bienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cambiarPass_BienvenidaActionPerformed(evt);
            }
        });
        P_panelLeft_Bienvenida.add(B_cambiarPass_Bienvenida);
        B_cambiarPass_Bienvenida.setBounds(20, 320, 180, 40);

        L_ICON_Bienvenida.setIcon(new javax.swing.ImageIcon("C:\\Users\\victo\\Documents\\GitHub\\pr-ctica-2-6-pantalla-de-login-lp-victor\\Login\\media\\th-2597715608.png")); // NOI18N
        P_panelLeft_Bienvenida.add(L_ICON_Bienvenida);
        L_ICON_Bienvenida.setBounds(60, 50, 100, 100);

        B_cerrarSesion_Bienvenida.setBackground(new java.awt.Color(255, 238, 217));
        B_cerrarSesion_Bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B_cerrarSesion_Bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        B_cerrarSesion_Bienvenida.setText("Cerrar Sesion");
        B_cerrarSesion_Bienvenida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_cerrarSesion_Bienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cerrarSesion_BienvenidaActionPerformed(evt);
            }
        });
        P_panelLeft_Bienvenida.add(B_cerrarSesion_Bienvenida);
        B_cerrarSesion_Bienvenida.setBounds(20, 440, 180, 40);

        B_cuentaNueva_Bienvenida.setBackground(new java.awt.Color(255, 238, 217));
        B_cuentaNueva_Bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B_cuentaNueva_Bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        B_cuentaNueva_Bienvenida.setText("Cuenta Nueva");
        B_cuentaNueva_Bienvenida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_cuentaNueva_Bienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cuentaNueva_BienvenidaActionPerformed(evt);
            }
        });
        P_panelLeft_Bienvenida.add(B_cuentaNueva_Bienvenida);
        B_cuentaNueva_Bienvenida.setBounds(20, 380, 180, 40);

        L_userLog_Bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_userLog_Bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        L_userLog_Bienvenida.setText("Usuario loggeado:");
        P_panelLeft_Bienvenida.add(L_userLog_Bienvenida);
        L_userLog_Bienvenida.setBounds(40, 180, 130, 20);

        TF_nombreUsuario_Bienvenida.setEditable(false);
        TF_nombreUsuario_Bienvenida.setBackground(new java.awt.Color(57, 167, 255));
        TF_nombreUsuario_Bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P_panelLeft_Bienvenida.add(TF_nombreUsuario_Bienvenida);
        TF_nombreUsuario_Bienvenida.setBounds(60, 210, 90, 20);

        P_panelTop_Bienvenida.setBackground(new java.awt.Color(135, 196, 255));
        P_panelTop_Bienvenida.setLayout(null);

        L_ICON_Min_MenuLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 55)); // NOI18N
        L_ICON_Min_MenuLogin.setForeground(new java.awt.Color(255, 238, 217));
        L_ICON_Min_MenuLogin.setText(" _");
        L_ICON_Min_MenuLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_ICON_Min_MenuLoginMouseClicked(evt);
            }
        });
        P_panelTop_Bienvenida.add(L_ICON_Min_MenuLogin);
        L_ICON_Min_MenuLogin.setBounds(750, 0, 40, 50);

        L_ICON_X_MenuLogin1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 35)); // NOI18N
        L_ICON_X_MenuLogin1.setForeground(new java.awt.Color(255, 238, 217));
        L_ICON_X_MenuLogin1.setText(" X");
        L_ICON_X_MenuLogin1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        L_ICON_X_MenuLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_ICON_X_MenuLogin1MouseClicked(evt);
            }
        });
        P_panelTop_Bienvenida.add(L_ICON_X_MenuLogin1);
        L_ICON_X_MenuLogin1.setBounds(800, 20, 34, 30);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENID@");
        P_panelTop_Bienvenida.add(jLabel1);
        jLabel1.setBounds(280, 10, 280, 50);

        TA_infoArchivo_Bienvenida.setBackground(new java.awt.Color(224, 244, 255));
        TA_infoArchivo_Bienvenida.setColumns(20);
        TA_infoArchivo_Bienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TA_infoArchivo_Bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        TA_infoArchivo_Bienvenida.setRows(5);
        TA_infoArchivo_Bienvenida.setBorder(null);
        SP_infoArchivo_Bienvenida.setViewportView(TA_infoArchivo_Bienvenida);

        MB_barraMenu_Bienvenida.setBackground(new java.awt.Color(135, 196, 255));
        MB_barraMenu_Bienvenida.setBorder(null);
        MB_barraMenu_Bienvenida.setForeground(new java.awt.Color(0, 0, 0));

        M_archivo_Bienvenida.setText("Archivo");

        MI_abrir_bienvenida.setBackground(new java.awt.Color(135, 196, 255));
        MI_abrir_bienvenida.setText("Abrir");
        MI_abrir_bienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_abrir_bienvenidaActionPerformed(evt);
            }
        });
        M_archivo_Bienvenida.add(MI_abrir_bienvenida);

        MI_guardar_Bienvenida.setBackground(new java.awt.Color(135, 196, 255));
        MI_guardar_Bienvenida.setText("Guardar");
        MI_guardar_Bienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_guardar_BienvenidaActionPerformed(evt);
            }
        });
        M_archivo_Bienvenida.add(MI_guardar_Bienvenida);

        MB_barraMenu_Bienvenida.add(M_archivo_Bienvenida);

        M_edicion_Bienvenida.setText("Edición");

        MI_cambColorUI_Bienvenida.setBackground(new java.awt.Color(135, 196, 255));
        MI_cambColorUI_Bienvenida.setText("Cambiar color a la interfaz");
        MI_cambColorUI_Bienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_cambColorUI_BienvenidaActionPerformed(evt);
            }
        });
        M_edicion_Bienvenida.add(MI_cambColorUI_Bienvenida);

        MB_barraMenu_Bienvenida.add(M_edicion_Bienvenida);

        setJMenuBar(MB_barraMenu_Bienvenida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_panelTop_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(P_panelLeft_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SP_infoArchivo_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(P_panelTop_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_panelLeft_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SP_infoArchivo_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_cerrarSesion_BienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cerrarSesion_BienvenidaActionPerformed
        this.dispose();
     }//GEN-LAST:event_B_cerrarSesion_BienvenidaActionPerformed

    private void B_cuentaNueva_BienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cuentaNueva_BienvenidaActionPerformed
        abrirCrearCuentaNueva(TA_infoArchivo_Bienvenida.getBackground());
    }//GEN-LAST:event_B_cuentaNueva_BienvenidaActionPerformed

    private void B_cambiarPass_BienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cambiarPass_BienvenidaActionPerformed
        abrirCambiarContrasena(TA_infoArchivo_Bienvenida.getBackground());
    }//GEN-LAST:event_B_cambiarPass_BienvenidaActionPerformed

    private void L_ICON_Min_MenuLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ICON_Min_MenuLoginMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_L_ICON_Min_MenuLoginMouseClicked

    private void L_ICON_X_MenuLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ICON_X_MenuLogin1MouseClicked
        this.dispose();
    }//GEN-LAST:event_L_ICON_X_MenuLogin1MouseClicked

    private void MI_abrir_bienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_abrir_bienvenidaActionPerformed
        // Selecionar el fichero a leer
        JFileChooser abrirFile = new JFileChooser();
        int seleccion = abrirFile.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == seleccion) {
            File archivoAbrir = abrirFile.getSelectedFile();

            // Leer el fichero y crear el contenido con el StringBuilder
            try (FileReader leerFichero = new FileReader(archivoAbrir)) {
                StringBuilder contenido = new StringBuilder();

                int caracter; // El FileReader devuelve los valor de ascii de los caractertes 
                while ((caracter = leerFichero.read()) != -1) { // Lee hasta que no encuentre un valor
                    contenido.append((char) caracter); // Castear y meterlo en el StringBuilder
                }
                TA_infoArchivo_Bienvenida.setText(contenido.toString()); // Imprimirlo por pantalla en el TextArea
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_MI_abrir_bienvenidaActionPerformed

    private void MI_cambColorUI_BienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_cambColorUI_BienvenidaActionPerformed
        this.dispose();
        abrirCambiarColor();
    }//GEN-LAST:event_MI_cambColorUI_BienvenidaActionPerformed

    private void MI_guardar_BienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_guardar_BienvenidaActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(null);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try (FileWriter writer = new FileWriter(archivo)) {
                writer.write(TA_infoArchivo_Bienvenida.getText());
                JOptionPane.showMessageDialog(null, "Archivo guardado con éxito.");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al guardar el archivo.");
            }
        }
    }//GEN-LAST:event_MI_guardar_BienvenidaActionPerformed

    private void bienvenida() {
        TF_nombreUsuario_Bienvenida.setText(usuarioLogeado.getUsuario());
    }

    public void cambiarColorInterfaz(Color colorBase) {
        TA_infoArchivo_Bienvenida.setBackground(colorBase);
        P_panelLeft_Bienvenida.setBackground(colorBase.darker().darker());
        P_panelTop_Bienvenida.setBackground(colorBase.darker());
        TF_nombreUsuario_Bienvenida.setBackground(colorBase);
        B_cambiarPass_Bienvenida.setBackground(colorBase.brighter().brighter());
        B_cerrarSesion_Bienvenida.setBackground(colorBase.brighter().brighter());
        B_cuentaNueva_Bienvenida.setBackground(colorBase.brighter().brighter());
    }

    public static void habilitarArrastre(JFrame frame) {
        frame.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                mousePressed = true;
                mouseX = e.getX();
                mouseY = e.getY();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                mousePressed = false;
            }
        });

        frame.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                if (mousePressed) {
                    int x = e.getXOnScreen();
                    int y = e.getYOnScreen();
                    frame.setLocation(x - mouseX, y - mouseY);
                }
            }
        });
    }

    private void abrirCambiarContrasena(Color colorFondo) {
        CambiarContrasena cambiarContrasena = new CambiarContrasena(usuarioLogeado, colorFondo);
        cambiarContrasena.setVisible(true);
        cambiarContrasena.pack();
        cambiarContrasena.setLocationRelativeTo(this);
    }

    private void abrirCrearCuentaNueva(Color colorFondo) {
        AgregarUsuario agregarUsuario = new AgregarUsuario(colorFondo);
        agregarUsuario.setVisible(true);
        agregarUsuario.pack();
        agregarUsuario.setLocationRelativeTo(this);
    }

    private void abrirCambiarColor() {
        CambiarColorInterfaz CCI = new CambiarColorInterfaz(usuarioLogeado);
        CCI.setVisible(true);
        CCI.pack();
        CCI.setLocationRelativeTo(this);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_cambiarPass_Bienvenida;
    private javax.swing.JButton B_cerrarSesion_Bienvenida;
    private javax.swing.JButton B_cuentaNueva_Bienvenida;
    private javax.swing.JLabel L_ICON_Bienvenida;
    private javax.swing.JLabel L_ICON_Min_MenuLogin;
    private javax.swing.JLabel L_ICON_X_MenuLogin1;
    private javax.swing.JLabel L_userLog_Bienvenida;
    private javax.swing.JMenuBar MB_barraMenu_Bienvenida;
    private javax.swing.JMenuItem MI_abrir_bienvenida;
    private javax.swing.JMenuItem MI_cambColorUI_Bienvenida;
    private javax.swing.JMenuItem MI_guardar_Bienvenida;
    private javax.swing.JMenu M_archivo_Bienvenida;
    private javax.swing.JMenu M_edicion_Bienvenida;
    private javax.swing.JPanel P_panelLeft_Bienvenida;
    private javax.swing.JPanel P_panelTop_Bienvenida;
    private javax.swing.JScrollPane SP_infoArchivo_Bienvenida;
    private javax.swing.JTextArea TA_infoArchivo_Bienvenida;
    private javax.swing.JTextField TF_nombreUsuario_Bienvenida;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
