/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import AccesoDatos.JDBCUsuario;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class CambiarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form CambiarContrasena
     */
    private Usuario usuarioLogeado;
    private JDBCUsuario aux = new JDBCUsuario();
    private static int mouseX, mouseY;
    private static boolean mousePressed;

    public CambiarContrasena() {
        initComponents();

    }

    public CambiarContrasena(Usuario usuarioLogeado_e) {
        this.usuarioLogeado = usuarioLogeado_e;
        initComponents();
    }
    
    public CambiarContrasena(Usuario usuarioLogeado_e, Color colorFondo) {
        this.usuarioLogeado = usuarioLogeado_e;
        initComponents();
        cambiarColorPrincpal(colorFondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        B_cambiar_CambiarContrasena = new javax.swing.JButton();
        L_infoCambiarContraseña_CambiarContrasena = new javax.swing.JLabel();
        TF_contrasenaNueva_CambiarContrasena = new javax.swing.JTextField();
        B_volver_CambiarContrasena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(224, 244, 255));

        B_cambiar_CambiarContrasena.setBackground(new java.awt.Color(255, 238, 217));
        B_cambiar_CambiarContrasena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B_cambiar_CambiarContrasena.setForeground(new java.awt.Color(0, 0, 0));
        B_cambiar_CambiarContrasena.setText("Cambiar");
        B_cambiar_CambiarContrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_cambiar_CambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cambiar_CambiarContrasenaActionPerformed(evt);
            }
        });

        L_infoCambiarContraseña_CambiarContrasena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_infoCambiarContraseña_CambiarContrasena.setForeground(new java.awt.Color(0, 0, 0));
        L_infoCambiarContraseña_CambiarContrasena.setText("Introduce la nueva contraseña:");

        TF_contrasenaNueva_CambiarContrasena.setBackground(new java.awt.Color(135, 196, 255));
        TF_contrasenaNueva_CambiarContrasena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TF_contrasenaNueva_CambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        TF_contrasenaNueva_CambiarContrasena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 167, 255), 2, true));
        TF_contrasenaNueva_CambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_contrasenaNueva_CambiarContrasenaActionPerformed(evt);
            }
        });

        B_volver_CambiarContrasena.setBackground(new java.awt.Color(255, 238, 217));
        B_volver_CambiarContrasena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B_volver_CambiarContrasena.setForeground(new java.awt.Color(0, 0, 0));
        B_volver_CambiarContrasena.setText("Volver");
        B_volver_CambiarContrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_volver_CambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_volver_CambiarContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(L_infoCambiarContraseña_CambiarContrasena))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(TF_contrasenaNueva_CambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(B_volver_CambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(B_cambiar_CambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(L_infoCambiarContraseña_CambiarContrasena)
                .addGap(20, 20, 20)
                .addComponent(TF_contrasenaNueva_CambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_volver_CambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_cambiar_CambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_cambiar_CambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cambiar_CambiarContrasenaActionPerformed
        if (TF_contrasenaNueva_CambiarContrasena.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El campo nueva contraseña no puede estar vacío.");
        } else {
            if (aux.actualizarPassword(usuarioLogeado.getUsuario(), TF_contrasenaNueva_CambiarContrasena.getText())) {
                JOptionPane.showMessageDialog(this, "Se ha actualizado la contraseña correctamente");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al cambiar la contraseña.");
            }
        }
    }//GEN-LAST:event_B_cambiar_CambiarContrasenaActionPerformed

    private void TF_contrasenaNueva_CambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_contrasenaNueva_CambiarContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_contrasenaNueva_CambiarContrasenaActionPerformed

    private void B_volver_CambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_volver_CambiarContrasenaActionPerformed
        this.dispose();
    }//GEN-LAST:event_B_volver_CambiarContrasenaActionPerformed

    public static void habilitarArrastre(JFrame frame) {
        frame.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                mousePressed = true;
                mouseX = e.getX();
                mouseY = e.getY();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                mousePressed = false;
            }
        });

        frame.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                if (mousePressed) {
                    int x = e.getXOnScreen();
                    int y = e.getYOnScreen();
                    frame.setLocation(x - mouseX, y - mouseY);
                }
            }
        });
    }

    public void cambiarColorPrincpal(Color colorBase) {
        jPanel1.setBackground(colorBase);
        B_cambiar_CambiarContrasena.setBackground(colorBase.brighter());
        B_volver_CambiarContrasena.setBackground(colorBase.brighter());
        TF_contrasenaNueva_CambiarContrasena.setBackground(colorBase.darker());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_cambiar_CambiarContrasena;
    private javax.swing.JButton B_volver_CambiarContrasena;
    private javax.swing.JLabel L_infoCambiarContraseña_CambiarContrasena;
    private javax.swing.JTextField TF_contrasenaNueva_CambiarContrasena;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
