package frames;

import AccesoDatos.JDBCUsuario;
import Modelo.Usuario;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author victor
 */
public class MenuLogin extends javax.swing.JFrame {

    JDBCUsuario DBaux = new JDBCUsuario();
    private Usuario usuarioLogeado;
    private AgregarUsuario agregarUsuario;
    private Bienvenida bienvenida;
    private static int mouseX, mouseY;
    private static boolean mousePressed;

    /**
     * Creates new form menuLogin
     */
    public MenuLogin() {
        initComponents();
        habilitarArrastre(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        P_panelTop_MenuLogin = new javax.swing.JPanel();
        L_ICON_Min_MenuLogin = new javax.swing.JLabel();
        L_ICON_X_MenuLogin1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        P_panelBot_MenuLogin = new javax.swing.JPanel();
        L_CLICK_nuevoUsuario_menuLogin1 = new javax.swing.JLabel();
        L_infoLogin_menuLogin = new javax.swing.JLabel();
        L_usuario_menuLogin = new javax.swing.JLabel();
        L_contraseña_menuLogin = new javax.swing.JLabel();
        TF_usuario_menuLogin = new javax.swing.JTextField();
        B_acceder_menuLogin = new javax.swing.JButton();
        CB_mostrarContrasena_menuLogin = new javax.swing.JCheckBox();
        PF_contrasena_menuLogin = new javax.swing.JPasswordField();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 91, 65));
        setUndecorated(true);

        P_panelTop_MenuLogin.setBackground(new java.awt.Color(135, 196, 255));
        P_panelTop_MenuLogin.setLayout(null);

        L_ICON_Min_MenuLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 55)); // NOI18N
        L_ICON_Min_MenuLogin.setForeground(new java.awt.Color(255, 238, 217));
        L_ICON_Min_MenuLogin.setText(" _");
        L_ICON_Min_MenuLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_ICON_Min_MenuLoginMouseClicked(evt);
            }
        });
        P_panelTop_MenuLogin.add(L_ICON_Min_MenuLogin);
        L_ICON_Min_MenuLogin.setBounds(570, 0, 40, 50);

        L_ICON_X_MenuLogin1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 35)); // NOI18N
        L_ICON_X_MenuLogin1.setForeground(new java.awt.Color(255, 238, 217));
        L_ICON_X_MenuLogin1.setText(" X");
        L_ICON_X_MenuLogin1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        L_ICON_X_MenuLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_ICON_X_MenuLogin1MouseClicked(evt);
            }
        });
        P_panelTop_MenuLogin.add(L_ICON_X_MenuLogin1);
        L_ICON_X_MenuLogin1.setBounds(620, 20, 34, 30);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        P_panelTop_MenuLogin.add(jLabel1);
        jLabel1.setBounds(270, 10, 140, 50);

        P_panelBot_MenuLogin.setBackground(new java.awt.Color(224, 244, 255));
        P_panelBot_MenuLogin.setPreferredSize(new java.awt.Dimension(650, 404));
        P_panelBot_MenuLogin.setLayout(null);

        L_CLICK_nuevoUsuario_menuLogin1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_CLICK_nuevoUsuario_menuLogin1.setForeground(new java.awt.Color(0, 0, 0));
        L_CLICK_nuevoUsuario_menuLogin1.setText("<html><b><u>Pulsa aquí para registrarte</u></b></html>");
        L_CLICK_nuevoUsuario_menuLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_CLICK_nuevoUsuario_menuLogin1MouseClicked(evt);
            }
        });
        P_panelBot_MenuLogin.add(L_CLICK_nuevoUsuario_menuLogin1);
        L_CLICK_nuevoUsuario_menuLogin1.setBounds(230, 340, 230, 25);

        L_infoLogin_menuLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_infoLogin_menuLogin.setForeground(new java.awt.Color(0, 0, 0));
        L_infoLogin_menuLogin.setText("Porfavor, introduzca sus credenciales para acceder:");
        P_panelBot_MenuLogin.add(L_infoLogin_menuLogin);
        L_infoLogin_menuLogin.setBounds(60, 40, 436, 25);

        L_usuario_menuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_usuario_menuLogin.setForeground(new java.awt.Color(0, 0, 0));
        L_usuario_menuLogin.setText("Usuario:");
        P_panelBot_MenuLogin.add(L_usuario_menuLogin);
        L_usuario_menuLogin.setBounds(60, 120, 60, 30);

        L_contraseña_menuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_contraseña_menuLogin.setForeground(new java.awt.Color(0, 0, 0));
        L_contraseña_menuLogin.setText("Contraseña:");
        P_panelBot_MenuLogin.add(L_contraseña_menuLogin);
        L_contraseña_menuLogin.setBounds(60, 200, 81, 30);

        TF_usuario_menuLogin.setBackground(new java.awt.Color(135, 196, 255));
        TF_usuario_menuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TF_usuario_menuLogin.setForeground(new java.awt.Color(255, 255, 255));
        TF_usuario_menuLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 167, 255), 2, true));
        TF_usuario_menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_usuario_menuLoginActionPerformed(evt);
            }
        });
        P_panelBot_MenuLogin.add(TF_usuario_menuLogin);
        TF_usuario_menuLogin.setBounds(190, 120, 300, 30);

        B_acceder_menuLogin.setBackground(new java.awt.Color(255, 238, 217));
        B_acceder_menuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B_acceder_menuLogin.setForeground(new java.awt.Color(0, 0, 0));
        B_acceder_menuLogin.setText("Acceder");
        B_acceder_menuLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_acceder_menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_acceder_menuLoginActionPerformed(evt);
            }
        });
        P_panelBot_MenuLogin.add(B_acceder_menuLogin);
        B_acceder_menuLogin.setBounds(190, 270, 301, 40);

        CB_mostrarContrasena_menuLogin.setBackground(new java.awt.Color(224, 244, 255));
        CB_mostrarContrasena_menuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CB_mostrarContrasena_menuLogin.setForeground(new java.awt.Color(0, 0, 0));
        CB_mostrarContrasena_menuLogin.setText("Mostrar");
        CB_mostrarContrasena_menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_mostrarContrasena_menuLoginActionPerformed(evt);
            }
        });
        P_panelBot_MenuLogin.add(CB_mostrarContrasena_menuLogin);
        CB_mostrarContrasena_menuLogin.setBounds(530, 200, 80, 30);

        PF_contrasena_menuLogin.setBackground(new java.awt.Color(135, 196, 255));
        PF_contrasena_menuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PF_contrasena_menuLogin.setForeground(new java.awt.Color(255, 255, 255));
        PF_contrasena_menuLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 167, 255), 2, true));
        PF_contrasena_menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF_contrasena_menuLoginActionPerformed(evt);
            }
        });
        P_panelBot_MenuLogin.add(PF_contrasena_menuLogin);
        PF_contrasena_menuLogin.setBounds(190, 200, 301, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_panelTop_MenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(P_panelBot_MenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(P_panelTop_MenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P_panelBot_MenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void L_CLICK_nuevoUsuario_menuLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_CLICK_nuevoUsuario_menuLogin1MouseClicked
        agregarUsuario.setVisible(true);
    }//GEN-LAST:event_L_CLICK_nuevoUsuario_menuLogin1MouseClicked

    private void B_acceder_menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_acceder_menuLoginActionPerformed
        String user = TF_usuario_menuLogin.getText();
        String pass = PF_contrasena_menuLogin.getText();
        if (DBaux.buscarUsuario(user, pass)) {
            usuarioLogeado = new Usuario(user, pass);
            abrirBienvenida(usuarioLogeado);
            this.dispose();
        }
    }//GEN-LAST:event_B_acceder_menuLoginActionPerformed

    private void CB_mostrarContrasena_menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_mostrarContrasena_menuLoginActionPerformed
        mostrarContraseña(CB_mostrarContrasena_menuLogin, PF_contrasena_menuLogin);
    }//GEN-LAST:event_CB_mostrarContrasena_menuLoginActionPerformed

    private void PF_contrasena_menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF_contrasena_menuLoginActionPerformed
        B_acceder_menuLoginActionPerformed(evt);
    }//GEN-LAST:event_PF_contrasena_menuLoginActionPerformed

    private void L_ICON_X_MenuLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ICON_X_MenuLogin1MouseClicked
        this.dispose();
    }//GEN-LAST:event_L_ICON_X_MenuLogin1MouseClicked

    private void L_ICON_Min_MenuLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ICON_Min_MenuLoginMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_L_ICON_Min_MenuLoginMouseClicked

    private void TF_usuario_menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_usuario_menuLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_usuario_menuLoginActionPerformed

    private void mostrarContraseña(JCheckBox check, JPasswordField pass) {
        if (check.isSelected()) {
            pass.setEchoChar((char) 0);
        } else {
            pass.setEchoChar('\u2022');
        }
    }

    private void abrirBienvenida(Usuario user) {
        bienvenida = new Bienvenida(user);
        bienvenida.setVisible(true);
        bienvenida.setLocationRelativeTo(this);
        bienvenida.pack();
    }

    private void abrirAgregarUsuario() {
        agregarUsuario = new AgregarUsuario();
        agregarUsuario.setVisible(true);
        agregarUsuario.pack();
        agregarUsuario.setLocationRelativeTo(this);
    }
    

    public static void habilitarArrastre(JFrame frame) {
        frame.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                mousePressed = true;
                mouseX = e.getX();
                mouseY = e.getY();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                mousePressed = false;
            }
        });

        frame.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                if (mousePressed) {
                    int x = e.getXOnScreen();
                    int y = e.getYOnScreen();
                    frame.setLocation(x - mouseX, y - mouseY);
                }
            }
        });
    }
    
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        JDBCUsuario aux = new JDBCUsuario();

        aux.conectarBBDD();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
        aux.desconectarBBDD();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_acceder_menuLogin;
    private javax.swing.JCheckBox CB_mostrarContrasena_menuLogin;
    private javax.swing.JLabel L_CLICK_nuevoUsuario_menuLogin1;
    private javax.swing.JLabel L_ICON_Min_MenuLogin;
    private javax.swing.JLabel L_ICON_X_MenuLogin1;
    private javax.swing.JLabel L_contraseña_menuLogin;
    private javax.swing.JLabel L_infoLogin_menuLogin;
    private javax.swing.JLabel L_usuario_menuLogin;
    private javax.swing.JPasswordField PF_contrasena_menuLogin;
    private javax.swing.JPanel P_panelBot_MenuLogin;
    private javax.swing.JPanel P_panelTop_MenuLogin;
    private javax.swing.JTextField TF_usuario_menuLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
